# Delivery management service, version 1.3.2

app:
  name: delivery
  hostname: moving
  replicas: 3
  port: 80
  registry:
    url: registry.docker.cube.int:5000
  image:
    name: delivery 
    tag: 1.3.2
  env:
    - name: ENVIRONMENT
      value: PRODUCTION
    - name: DEBUG
      value: "false"